const AIBriefing = () => {
  const riskScore = 80;

  return (
    <div className="border border-cyan-500/30 bg-cyan-500/5 rounded-sm p-4">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-cyan-400 font-bold tracking-widest">
          AI SITUATION REPORT
        </h3>

        <span className="text-xs text-cyan-300">
          LIVE
        </span>
      </div>

      <div className="space-y-3 text-sm">
        <p>
          <span className="font-bold text-white">Location:</span> Chennai
        </p>

        <p>
          <span className="font-bold text-white">Risk Score:</span>{" "}
          {riskScore}/100
        </p>

        <p>
  <span className="font-bold text-white">Primary Threat:</span>{" "}
  Critical Multi-Hazard Event
</p>

        <p>
          <span className="font-bold text-white">Expected Impact:</span>{" "}
          High
        </p>

        <p>
          <span className="font-bold text-white">Recommendation:</span>
        </p>

        <ul className="ml-4 list-disc text-neutral-300">
          <li>Deploy emergency response units</li>
          <li>Increase flood monitoring</li>
          <li>Prepare evacuation routes</li>
        </ul>

        <p className="text-xs opacity-50 pt-2">
          Generated by Averra AI
        </p>
      </div>
    </div>
  );
};

export default AIBriefing;